export const tableHeadItems = [
  "VIM",
  "Tipo",
  "Status",
  "Prioridade",
  "Agente",
  "Adicionado",
  "Vencimento",
  "Motivo da Exceção",
  "Nome",
];

export const nfs = [
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
  {
    vim: "123456789",
    tipo: "NF",
    status: "Em tratamento",
    prioridade: "Urgente",
    agente: "Rick Wright",
    adicionado: "01/01/2020",
    vencimento: "Integer",
    motivo: "Aliquet",
    nome: "Posuere",
  },
];
